name: edag-cli-dev
channels:
    - elasticdag
    - conda-forge
    - defaults
dependencies:
    - python
    - pip

    # Setup Requirements (setup.py:setup_requirements)
    - pytest-runner 5
    - wheel

    # Install Requirements (setup.py:requirements)
    - click >=7.0
    - click-plugins
    - entrypoints

    # Test Requirements (setup.py:test_requirements)
    - pytest >=3
    - pytest-cov

    # Documentation Requirements
    - sphinx
    - watchdog

    # Dev Workflow requirements
    - black
    - flake8
    - bump2version==0.5.11
    - twine


