name: edag-cli-dev
channels:
- conda-forge
- defaults
dependencies:
#
# Dependencies must be kept in sync with setup.py
- python
# Setup Requirements
- pytest-runner 5
- wheel

# Install Requirements
- click 7
- click-plugins
- entrypoints

# Test Requirements
- black
- coverage
- flake8==3.7.8
- pytest 4.6
- pytest-cov

# Documentation Requirements
- sphinx
- watchdog

# Other Requirements
- bump2version==0.5.11
- pip
- twine


