name: edag-cli-dev
channels:
- conda-forge
- defaults
dependencies:
- python
- pip
- entrypoints
- click 7
- click-plugins
# Development / Test / Docs
- black
- bump2version==0.5.11
- coverage
- flake8==3.7.8
- pytest 4.6
- pytest-cov
- pytest-runner 5
- sphinx
- twine

