
{% set data = load_setup_py_data() %}

package:
  name: edag-cli
  
  version: {{ data['version'] }}

source:
  path: ..

build:
  # If the installation is complex, or different between Unix and Windows, use
  # separate bld.bat and build.sh files instead of this key.  Add the line
  # "skip: True  # [py<35]" (for example) to limit to Python 3.5 and newer, or
  # "skip: True  # [not win]" to limit to Windows.
  script: {{ PYTHON }} -m pip install --no-deps --ignore-installed -vv .
  noarch: python
  
  

requirements:
  # if you need compilers, uncomment these
  #    read more at https://docs.conda.io/projects/conda-build/en/latest/resources/compiler-tools.html
  # build:
  #   - {{ compilers('c') }}
  host:
    - python {{ data['python_requires'] }}
    - pip
    {% for dep in data['setup_requires'] %}
    - {{ dep.lower() }}
    {% endfor %}
    {# raw is for ignoring templating with cookiecutter, leaving it for use with conda-build #}
  run:
    - python
    # dependencies are defined in setup.py
    {% for dep in data['install_requires'] %}
    - {{ dep.lower() }}
    {% endfor %}

test:
  source_files:
    - tests
  requires:
    - pytest
    - pytest-cov
    # dependencies are defined in setup.py
    {% for dep in data['tests_require'] %}
    - {{ dep.lower() }}
    {% endfor %}

  commands:
    - pytest tests

about:
  home: https://github.com/sodre/edag-cli
  summary: ElasticDAG CLI is the entry point for all of ElasticDAG tools.
  license: {{ data.get('license') }}
  license_file: LICENSE
