name: Python package

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [3.7]
        #os: [ubuntu-latest, windows-latest, macOS-latest]
        #python-version: [3.6, 3.7, 3.8]
    name: Python ${{ matrix.python-version }} example
    steps:
      - uses: actions/checkout@master
      - name: Setup conda
        uses: s-weigand/setup-conda@master
        with:
          update-conda: true
          conda-channels: anaconda, conda-forge
      - run: conda init bash
      - run: conda env create .
      - run: source activate edag-cli-dev && make test
