name: release publisher
on:
  release:
    types: [published]
jobs:
  one:
    runs-on: ubuntu-16.04
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Dump job context
        env:
          JOB_CONTEXT: ${{ toJson(job) }}
        run: echo "$JOB_CONTEXT"
      - name: Dump steps context
        env:
          STEPS_CONTEXT: ${{ toJson(steps) }}
        run: echo "$STEPS_CONTEXT"
      - name: Dump runner context
        env:
          RUNNER_CONTEXT: ${{ toJson(runner) }}
        run: echo "$RUNNER_CONTEXT"
      - name: Dump strategy context
        env:
          STRATEGY_CONTEXT: ${{ toJson(strategy) }}
        run: echo "$STRATEGY_CONTEXT"
      - name: Dump matrix context
        env:
          MATRIX_CONTEXT: ${{ toJson(matrix) }}
        run: echo "$MATRIX_CONTEXT"

  setuptools-publish:
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [3.7]
    name: setuptools py${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    if: github.event.action == 'published'
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-python@v1.1.1
      - uses: actions/cache@v1
        id: cache
        with:
          path: .eggs
          key: ${{  matrix.os }}-${{ matrix.python-version }}-eggs-${{ hashFiles('setup.py') }}
      - run: make dist
      - name: Upload assets to a Release
        uses: AButler/upload-release-assets@v2.0
        with:
          files: dist/*
          repo-token:  ${{ secrets.GITHUB_TOKEN }}
